name: Iris Fly Deploy
on:
  push: { branches: [ {branch} ] }
  workflow_dispatch: {}
jobs:
  fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          if [ -f Dockerfile ]; then
            flyctl deploy --remote-only --build-arg GIT_SHA=${{ github.sha }}
          else
            echo 'No Dockerfile found.'; exit 1
          fi
